name: lol_spotify_companion
description: "Lol Spotify Companion"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  url_launcher: ^6.3.2
  http: ^1.5.0
  system_tray: ^2.0.3
  window_manager: ^0.3.7
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 256

flutter:
  uses-material-design: true
  assets:
    - assets/champions.json
    - assets/champions/
    - assets/i18n/
    - assets/app_icon.ico
    - assets/icon.png
